# Generated by Django 6.0.5 on 2026-06-05 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(default=datetime.datetime(2026, 6, 1, 0, 14, 41, 92506)),
        ),
    ]
